### ISSUE TITLE
微调NSF-HifiGAN，声谱高频部分有异常的横纹

### ISSUE THREAD

**Issue by atomicoo** [openvpi/SingingVocoders#2]
如题。

我按照文档的描述在自己的数据集上微调NSF-HifiGAN声码器，查看tblog时，发现在声谱高频部分会有异常的横纹出现：
![1](https://github.com/openvpi/SingingVocoders/assets/67351972/663a1313-f3be-424f-a37a-3a68b13148ed)
静音处显得更为明显：
![2](https://github.com/openvpi/SingingVocoders/assets/67351972/aa2a50f2-1e47-4e02-a13a-b9282576b266)

说明：我使用[ft_hifigan.yaml](https://github.com/openvpi/SingingVocoders/blob/main/configs%2Fft_hifigan.yaml)配置文件，除了数据集之外没有改变其他任何参数，使用的数据集大小~2小时。

对此有任何建议吗？thx~

**Comment by autumn-2-net** [comment]
事实上这属于正常情况，高频反向谐波在微调之前也是存在的，只不过没有这么明显
微调后明显，可能是由于用于微调的数据高频高频缺失导致的。
并且这种伪影 人大部分都是听不出来的，忽略即可
