### ISSUE TITLE
声码器无法很好地还原具有某些特质的音色？

### ISSUE THREAD

**Issue by atomicoo** [openvpi/SingingVocoders#7]
Hi~，我使用了[Releases](https://github.com/openvpi/SingingVocoders/releases)中发布的两个版本的声码器，发现两者都不能很好的还原下面音色。

原始录音：
[XYH（原始录音）.zip](https://github.com/openvpi/SingingVocoders/files/14477493/XYH.zip)

声码器重建波形：
[XYH（2022.12）.wav.zip](https://github.com/openvpi/SingingVocoders/files/14477496/XYH.2022.12.wav.zip)
[XYH（2024.02）.wav.zip](https://github.com/openvpi/SingingVocoders/files/14477497/XYH.2024.02.wav.zip)

原始录音中有明显的怒音特征，但是声码器重建的波形听起来则是嘶哑偏破音的状态。此外，即便是使用该音色的录音数据对声码器进行少量步数的针对性微调也没能完全解决这个问题（有所改善）。
我正在想办法看能否解决，对此您有任何想法吗？Thx~

**Comment by yxlllc** [comment]
看了下频谱，这种撕裂音的发声态包含大量 f0/2 甚至 f0/4 的亚基频谐波，已经远远超出 nsf 模型的表达能力，所以确实是模型局限性，微调也难以很好解决。
